ALTER TABLE "Wallet"
  ALTER COLUMN "balance" TYPE BIGINT USING ROUND("balance")::BIGINT,
  ALTER COLUMN "balance" SET DEFAULT 0;

ALTER TABLE "Transaction"
  ALTER COLUMN "amount" TYPE BIGINT USING ROUND("amount")::BIGINT;

ALTER TABLE "Budget"
  ALTER COLUMN "amount" TYPE BIGINT USING ROUND("amount")::BIGINT;

ALTER TABLE "RecurringBill"
  ALTER COLUMN "amount" TYPE BIGINT USING ROUND("amount")::BIGINT;
